# Generated by Django 2.2.6 on 2019-10-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like_Product',
        ),
    ]
