# Generated by Django 2.2.6 on 2019-11-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outer_Top',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.Product')),
                ('bust', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('armhole', models.IntegerField(default=0)),
                ('sleeve', models.IntegerField(default=0)),
                ('sleevewidth', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
            bases=('clothes.product',),
        ),
    ]
