# Generated by Django 2.2.6 on 2019-11-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_outer_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.Product')),
                ('waist', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('armhole', models.IntegerField(default=0)),
                ('sleeve', models.IntegerField(default=0)),
                ('sleevewidth', models.IntegerField(default=0)),
                ('hip', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
            bases=('clothes.product',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.Product')),
                ('waist', models.IntegerField(default=0)),
                ('hip', models.IntegerField(default=0)),
                ('thigh', models.IntegerField(default=0)),
                ('hem', models.IntegerField(default=0)),
                ('crotch_rise', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
            bases=('clothes.product',),
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.Product')),
                ('waist', models.IntegerField(default=0)),
                ('hip', models.IntegerField(default=0)),
                ('hem', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
            bases=('clothes.product',),
        ),
    ]
