# Generated by Django 2.2.6 on 2019-11-02 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0003_ops_pants_skirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clothes.Product')),
                ('bust', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('armhole', models.IntegerField(default=0)),
                ('sleeve', models.IntegerField(default=0)),
                ('sleevewidth', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
            bases=('clothes.product',),
        ),
        migrations.RenameModel(
            old_name='Outer_Top',
            new_name='Outer',
        ),
    ]
